<?php
/**
 * @author Magebit <info@magebit.com>
 * @copyright Copyright (c) Magebit, Ltd. (https://magebit.com)
 * @license https://magebit.com/code-license
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="field field-reserved w-full field-telephone required group">
    <label for="telephone"><?= $escaper->escapeHtml(__('Telephone')) ?></label>
    <div class="control relative">
        <input type="text"
               name="telephone"
               required
               placeholder="<?= $escaper->escapeHtml(__('Enter phone number')) ?>"
               id="telephone"
               class="form-input w-full"/>
    </div>
</div>
